import pandas as pd  # 引用套件並縮寫為 pd

dict = {  
    "RANK": "電影排行",
    "NO.1": "鬼滅之刃",
    "NO.2": "無聲",
    "NO.3": "刻在你心底的名字",
    "NO.4": "親愛的房客",
    "NO.5": "碧藍之海"
}
ax = """
                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                          
                                                                                                                       ``````.............``````                                                                                                          
                                                                                                                ``.-:/++sssyyyhhhhhhhhhyyyyssso++/:--..``                                                                                                 
                                                                                                          ``.-/+osyyhhhhhhhhhhhhhhhhhhhhhhhyhhhhhhhyyysso+/:.```                                                                                          
                                                                                                    ``.-:/osyhhhhhhhhhhhhhhhhhhhhhhhhyyyhhhhhhhhhhhhhhhhhhhyyyso/-..`                                                                                     
                                                                                                ``-:+syyhhhhhhddddddddddddmmmmmdddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyso/:.`                                                                                 
                                                                                             `.:osyhhhhhhdddddddddddhdddhhhddhhhhhhhhhhhhhdddmmddddddhhhhhhhhhhhhyhhhhyys+-``                                                                             
                                                                                          `-/oyhhhhhdddmmddhyysssssssoo+/:://odmNNNNmNNNNNNNNNNNNNNNNmmmdddhhhyyyyhhhhhhhhhyo/-.`                                                                         
                                                                                        ./syhhhhdmmmmmdysoo+//::-.`````..-+shdmNNNNmddhhyyyyhhddmNNMMNNNNNmmddhhhhyhhhhhhdhhhhyso/-``                                                                     
                                                                                     `-+yyhhdmNNmdyo+////-.``  ```.-://////::--...``.....--:-::/+osydNNMMMMMNNNNmmddhhhhhhhhdddhhhys+:-``                                                                 
                                                                                  `.:syhhdmNNdy+::::-.`      `.....``                           ```.-:+shdNMMMMNMMNNNmmdhhhhhhhdddhhhyyss+:-`                                                             
                                                                                `.+shhdmNNho:.`````                                                     ``.:+ydNMMMMMMNNNmmdhhhhhhdddhhyhyo/-`                                                            
                                                                              `-oyhhmNmh+-`                                                                   `./ohmNMMMMMNNNmdhhhhhhdddhhhyo:``                                                          
                                                                            `:oyhdmmd+-`                                                                          `-/sdNMMMMMNNNmdhhhhhhddhhhho:.                                                         
                                                                          `/syhdmdy:`                                                                                ``:ohNMMMMMMNNmdhhhhhddhhhyo:`                                                       
                                                                        ./shhdmdo-`                                                                                      `:sdNMMMMMNNmdhhhhhhdhhhyo.                                                      
                                                                      `:syhdmh+.`                                                                                          `-odNNMMMMMNmddhhhhhhhhhs-```                                                  
                                                                    `-oyhdmh+.                                                                                                ./ydNMMMMNNNddhhhhhdhhyo++:.`                                               
                                                                   ./yhdmdo.`  `-`                                                     ```                                 `.`.:++sdNMMMMNNmddhhhhhhhhhhyo:`                                              
                                                                 `.+ydmds-`   `:ss:.       `.` .:.`                         `        `--+h+...``     `               `:.   `oy+o:../ydNMMNNMNmddhhhhhhhhhs-`                                              
                                                                 `+hdmy:`     `/syyo/.     `+:`/ho:/-`       `-:--:.     `.::::`     :y/+o+--/y+`   .s:`    `-/-`    .y+`-/+sdy/`   .+ymNMMMMNNmddhhhhhhhy/.                                              
                                                                 :hmdo`       .+sssho.     `/y+ys.`-ho`  .:/ss/.`.+d:   ./:s/.o+` `:+shho:::+yh/`   `sh` ````:ym/`   .h/.-:-/y-`     `-odNMMMMMNmddhhhhhhhy+.                                             
                                                                `ymy:`        `:/++sh:     -sydd/``/ds`  `:/:. `./yy-   -os/.:s/   `--.-ss/--.`      :h/./+``-:/-    /do.`..+y:        `:ymNMMMMNNmddhhhhhhho-`                                           
                                                                -do.          .s++++:.     -oo+:::+s+.      `.:/+/:`    `...--.`        .sh:          :oshs`         :ms-/+ohhyo-        .sdNMMMMNNmddhhhhhhhs:-.                                         
                                                               `+:`            ./oo/`       ```.--.`         ```                         -y+           ``.`          `/:`.::-:/+-         `/hmMMMMMNNddhhyyhhhys+.`                                       
                                                               ``                                                                         ``   `---------------------:---------------------:+sdmmmmdddhdhhhhyyhhyo`                                       
                                               ```````                                    `-:--.``                                             /mNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNdhmmhhhhhhyhh/`                                      
                                              `+hhyyyssooo+//:`                           `:sdmdho:`                    .-..`                  /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhNNmhhhhhhhhy/`                                     
                                              :dMMMMMMMMMMNNms-                             `:yNMMm+                    :dmdh/` ./:-`          /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhNNNmhhyyyyhhs:`                                    
                                        `` ` .yNMMMMMMNMMMMh-``                        ``     .omMNy`                   .hMMm/` `:hmdo-        /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhNMNNdhyyhhhhhs-                                    
                               .+sssssssssssshNMMMMMMMMMMMNysssssssssssssssssssssssssssso.     `:s+.                    `yMMd.    -hNMd:       /mNNNNNNNNNNNNNNNNNNNNMMMMMNNNNNNNNNNNNNNNNNMMMMMMMMMMmhNMMNmdhhhyhyhy/`                                   
                               -dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm.           `://////////////////dMMm+/////oNMMy/:.    `--:-:-:-::-:-::-:-::sMMMMMo:--------::---:oNMMMMMMMMMmhNMMMNmhhhyyyhho.                                   
                               -dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm-           :mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm/                        `sMMMMN-              `/NMMMMMMMMMmhNMMMNmdhhhyhhhy/`                                  
                               -dMMMMMMMMmhssssssssssssssydMMMMMmysssssssssssssshNMMMMMMNho+:``    `//mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm/     ````               .hMMMMd.               +NMMMMMMMMMmhNMMMMNmhhhhhhyho`                                  
                               -dMMMMMMMNo`           `   :NMMMN:               `oNMMMMMNsmMNd+`  `/o/mMMMMMMMMMNNMNNNNNNMMMMMMMMNNNNNNMNm/     -oso+:.``          :dMMMMs`               +NMMMMMMMMMmhNMNMMNmhhhhhyhhs.                                  
                               -dMMMMMMMN+`               -mMMMm.               `/mMMMMMm./dMMN/  .h/:mMMMMMMd+///+++so+omMMMMMNy+/++++///.      `-+hmmds+-``     `+NMMMN/                +NMMMMMMMMMmhNMNNNMNmhhyhyhhy.`                                 
                               -dMMMMMMMN+`               -mMMMm.               `/mMMMMMN. :dNm:  +h.:mMMMMMMh`````-yNms/dMMMMMNo``//-.``           `.ohNMNmyo:.``.yNMMMd-                +NMMMMMMMMMddNMNmNMNNdhyhyhhh-`                                 
                               -dMMMMMMMNs.```````````````+NMMMN/```````````````.sNMMMMMN. `.-.  -hy :mMMMMMMmyyyyyhdmdmdmMMMMMNs`/NMNmdyo:`           `:sdMMMMmhosmMMMMy`                +NMMMMMMMMMddNMNmmmNNmhhyyhhh-`                                 
                               -dMMMMMMMMNmdhhhhhhhhhhhhddNMMMMMNddhhhhhhhhhhhddmNMMMMMMm-       +m: :mMMMMMMy.`.+o+:.``.sNMMMMNs.hMMMMMMy/`    `--.`     .+hNMMMMMMMMMm+`               `+NMMMMMMMMNddNNNdhdNNmdhhhhhh-`                                 
                               -dMMMMMMMMd+:-:--:::-::::::sNMMMMy::::::::--:::::+dMMMMMMN.    ` -dd. :mMMMMMMy` `hMNs.`-`+NMMMMMh+NMMMMNd-      +NNmo`      `:yNMMMMMMMm/`               `+NMMMMMMMMNddNddhhhdmdhhyhhhh-`                                 
                               -dMMMMMMMNo`               :mMMMm-               `+NMMMMMN.     `oNo` :mMMMMMMy:/`sMm:`oNhyNMMMMMmdMMMMMN+` :sssshMMNyssss:`   `-hMMMMMMMm+`               +MMMMMMMMMNddNhhhhyhhhhhhhhhh-`                                 
                               -dMMMMMMMNo`               -mMMMm.                /mMMMMMN.     -dm:  :mMMMMMNssh-oNN/omdoomMMMMMMMNMMMMs. `ommmmmmmmNMMMMh.     :NMMMMMMMNd/`            `+MMMMMMMMMNhdNhhyhhhhhyyyhhhh-`                                 
                               -dMMMMMMMNs`               -mMMMm.               `+NMMMMMN.     oNy. `/NMMMMMNdmm/sNMh+-` .yMMMMMMMMMMMd.   ```  ``:yNMNh:`      yNMMMMMMMMMNh:`          `oMMMMMMMMMNhmNhhyyyhhyyyyhhhh-                                  
                               -dMMMMMMMMd+--------------:sNMMMNs:--------------/hNMMMMMN.    -mNo` `oNMMMMMMNNh-sNm-     oNMMMMMMMMMm/        `/hNMms-`       :mMMMMNNMMMMMMmo`         `oMMMMMMMMMNhmNdhhyhhhhyyhhhyy.                                  
                               -dMMMMMMMMMNNNNNNNNNNNNNNNNMMMMMMMNNNNNNNNNNNNNNNNMMMMMMMm.   `oMd:  `yMMMMMMm/-``hMm+:.`  -dMMMMMMMMm/`      .odNNdo.`        .hMMMMm/-sNNMMMMNy`        `oMMMMMMMMMNhmNdhhyhhhhyhhhhhs.                                  
                               -dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm.   :mMy.  :dMMMMMMd. `+Nm/+dmy. .hMMMMMMMm/`    `-ymMMm+.`         .sNMMMm+  `oNMMMMMNy`       `sMMMMMMMMMNhmNdhhhhhhyyyhhhh+`                                  
                               -dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMm.  .hMN+`  oNMMMMMNs` :dh:  oNm:-sNMMMMMMm/`    -yNMNyoddysssooss/``oNMMMm+`   .sNMMMMMN+       `yMMMMMMMMMmhmNmhhhhhhyhhhhhh/`                                  
                               ./ooooooooo++oNMMMmso+++ohMMMMMMMMMNyoooooosysooooooooooo+` .yNMm-  -mMMMMMMm:`+hs.   `-:omMMMMMMMMmo`    .+ho-` :ymNNNNMNd-.sNMMMm+`     `yMMMMMNy.      `hMMMMMMMMNmhNNmhhhyhhhhhyhhs-                                   
                                            .NMMMNms.  `sNMMMMMMMMh-     `+Nmho-`     `.::ohNMMy. .yMMMMMMMy:oo-`   `-odNMMMMMMmhNMNy- `/:```    `.--::::-.yNMMMm/`       .hMMMMNo`      .mMMMMMMMMMdhMNmhhyyyyyhyyhy+.                                   
                                            .MMMMNh/`  `sNMMMMMMMNs`     `yMMNh+`      `-+hNMMNo``oNMMMMMMm/..`   `/smNMMMMMMNh:`:hNNmysmy.              -hNMMNd:`         -sdmdo.       .NMMMMMMMMMdhMNmhhhyhhhhyhyy:`                                   
                                            /MMMMs`    `sNMMMMMMMN/      :mNd/.`       :- .oNMMy.:dNMMMMMNo`     `/hNMMMMMMMd+.   ./hNMMMm+`           `+dNMMNs.            `..`         /NMMMMMMMMNhdMNmdhhhhhhyyhyo.                                    
                                           `hMMMd.     `sNMMMMMMMN/     `yNh-`.so:`   `s+` .hNMN+..:+ydNMs.       ``:odNMNdo-       ./ymNmo`          -yNMMNd/`                          yMMMMMMMMMNhmMNNmhhhyhhyyhy:`                                    
                                           /NMMN+`     `sNMMMMMMMm/ `` `/my.` `+NNh:` -hh. `sNMMd-   `.:+.            .:s+.`          `.--`        `.omMMMmo.                           -mMMMMMMMMMNyNMNdhhyyhhhhhh+`                                     
                                          .hMMMy.      `sNMMMMMMMN/-yyyymNyoosshNMMm/`/mN- `:dNNy.                                                .+dNMNms-`                           .sMMMMMMMMMMmyMMNmdhhyyyyhhs-`                                     
                                         `omMMd/`      `sNMMMMMMMNs-hNNNmdhso+/:sNMNo-hMNy-``-/:.                                              `.odNNNdo-`                 `.````  ```-sNMMMMMMMMMMsmMMMNNdhhyyhyh:`                                      
                                        `/mMMN+`       `sNMMMMMMMMmsodo:-.```` `.os+/hNMMMmy:`                                               `:sdNNmy/.`                   .ydhyyyyyyhmMMMMMMMMMMMmyMMMMNmdhhhhhho.                                       
                                        :dMMMs.        `sNMMMMMMMMMNNmdhysssssssyyhhmMMMMMMN+`                                            `.+ymNmy+-`                      `oNMMMMMMMMMMMMMMMMMMMNhmMMMNmhhhhhhhs-`                                       
                                       -dMMMh`         `oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy.                                          `-+yddho:.`                          -dMMMMMMMMMMMMMMMMMMNdhNMNNmhyhhyhhy/`                                        
                                     `-dMMNy.         ``:dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh-                                         ./syso:.`                              `sNMMMMMMMMMMMMMMMNNddNMNmdhhhhyhhy+.                                         
                                    `/dMMNs.          ::.+dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy-                                          `-.``                                   :mMMMMMMMMMMMMMNmdhmNMNdhhhyhhhyy+.                                          
                                   .omMMm+.           `oy+:+ydmmNNNNNNNNNNNNNNNNNNNNmdhs:`                                                                                   .yNNNNNNNNNmmmdddNMMMMmdhyyhhhhho.                                           
                                 `-hNMMd:`             .smd+-.--:::::::::::::::::::--.``                                                                                      .:::::+ydmmmmNNMMMMNNmhyhyyyhho.                                            
                               `.omMMms.              ` `omNdo-`                                                                                                                .--+dNMMMMMNNNNNNNmdhhhhhhy+.                                             
                              .+hNMNy:`                  `:hNNms:`                                                                                                             .smmNMMMMMNNmdmmdddhhhyhhhy+.`                                             
                            `/hNMNh/`                     `-smNNmy/.                                                                                                          .sNMMMMMMNNmdhhhhhhhhyyyyhy/``                                              
                          ./hNMmh/`                        `/ydmNNNdo-`                                                                                                     `/hMMMMMMMNmdhhhhyyhhhhyyyhy:`                                                
                       `.odNNms:`                           -shhdmNMMmy/.`                                                                                                `-ymMMMMMMNNmhhhyyhyhhhhyyyhs:`                                                 
                    `.:smNmh+.                              .+/oyhdmNNMNms:.`                                                                                           `-smMMMMMMMNmdhhyyyyyhhhhhhyso-`                                                  
                  `-sdNmh+-`                                `.``/yhhdmNNNNNds:.`                                                                                     .--omMMMMMMMNNmhhhhhhhhhhhyhhy+-``                                                   
               `:ohmdy+-`                                       `/syhhddmmmNNNds:.                                                                                ``/dmmNMMMMMMNNmdhhyyyyhhyyyyhyo:`                                                      
              `ydho:`                                            `-+yhyhhddddmNNNds:.                                                                           .:odNMMMMMMMNNNmdhhhhhhhyyyyyyyy+.`                                                       
               ..`                                               `-+yyhyyhhhddddmNNNdo-``                                                                    `-odNMMMMMMMNNmdddhhhyyhhhhhyyyhyho.                                                         
                                                                   `:shyyhhhhhhhhdmNNNNds:.`                                                               .:yNMMMMMMMMNNmdhhhhyyhhyhhhhhhhhhyo.`                                                         
                                                                    `-s+:shhyhyhhhhhdmNNMMmyo:.                                                          .+mNMMMMMMMNNmdhhhhhyyhhhhyyyyyyhhys+:-`                                                         
                                                                      ..`-ohyyyhyhhhhhhdmNNMMNmho:.``                                           ``./oo-./dNMMMMMMMNNmhhhhhyyyyyyhhyyyyyyhyso+/.`                                                          
                                                                         `.+yhyyyyyyhhhhhhdmNNNMMMNmyo/:.``                            `.-:://oshmNMMMNNMMMMMMMMNmdhhyyhhhhyyyyyyyyyhyysso/-``                                                            
                                                                           ./syhyhyyhhyhyhhhhddmNNNMMMMNNdhyo+:-.``                   .omNNNMMMMMMMMMMMMMNMNNNNNdhhhyyhhhhhhhhhhhhyho/-.``                                                                
                                                                            ``./syhhhhhhhhyyyhhhhhddmNNNMMMMMMMMNNNmmdhyyssssssssyyhhmNMMMMMMMMMMMMNNNNmmdddmddhhhhhhhhhyyyyyyhhyyo-`                                                                     
                                                                               ``-+syhyhyyyyhhhhhhhhhhhddmmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmmmmdddhhhhhhhhhhhyyyhhhhyyyyyyyhyo-`                                                                       
                                                                                 ``./yhhyyyhhhhhhyhhhhhyhhhhhhddmmmNNNNNNNNMMMMMMMMMNNNNNNNmdhhhhhhhhhhyyyhhhyyyhhhhhhyyyyysoo+/-`                                                                        
                                                                                   `-:/oyhyyyyyyyyhhyyyyhhyyyyhhhhhhhhhhdddddddddddddddddhhhhhhhyyhyyyyyyhhhhyyyysoo+::-.`````                                                                            
                                                                                     `:+syyhhhhhhhyhhyyyyyyyyyhhhhyyyyhyhhhhhhhhhhhhhhyhhhhyhhhhhhyhhyhyyo+//:--.````                                                                                     
                                                                                       ``.-:+syyyyhhyyyssssyyyyyyhhyyhhhhhhhhhhhhhhhhhhyyhyysssssssssoo/:.`                                                                                               
                                                                                         ``..-/shhyyy+-```.://::/oyyo++//++++++ooossoo++/:-.```````````                                                                                                   
                                                                                           `.:/oooo+-`        ` ``..````  `` ````````````                                                                                                                 
                                                                                               `````                                                                                                                                                      
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                          
  
"""


select = pd.Series(dict, index = dict.keys())   
print(select[0])  
print("=================================")  
print(select[[0, 1, 2,3,4,5]])  
print("=================================")  
print(select[[1]])  
print(ax)